# Generated by Django 3.2.7 on 2022-05-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='comentarios',
            new_name='comentario',
        ),
    ]
